#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestApp.Droid.Resource", IsApplication=true)]

namespace TestApp.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "12.3.99.16")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int sections = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int accent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int primary = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int primaryDark = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int window_background = 2130837507;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int card_margin = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int fab_margin = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int image_size = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int small_margin = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int standard_margin = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int tiny_margin = 2130903045;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int background_splash = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int circle_background = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int divider = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int heroplaceholder = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int ic_save = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int xamarin_logo = 2130968581;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050001
			public const int menu_edit = 2131034113;
			
			// aapt resource value: 0x7F050000
			public const int MoreStandardText = 2131034112;
			
			// aapt resource value: 0x7F050002
			public const int recycler_view = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int sliding_tabs = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int toolbar = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int main_layout = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int standard_cell = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int tabs = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int toolbar = 2131099651;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F070000
			public const int top_menus = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F080000
			public const int Icon = 2131230720;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int app_description = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int app_name = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int description = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int hello = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int hint_description = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int hint_name = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int info = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int learn_more = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int login = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int notnow = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int quantity = 2131296266;
			
			// aapt resource value: 0x7F09000C
			public const int signin = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int signing_in = 2131296269;
			
			// aapt resource value: 0x7F09000B
			public const int sign_in_text = 2131296267;
			
			// aapt resource value: 0x7F09000E
			public const int tab1 = 2131296270;
			
			// aapt resource value: 0x7F09000F
			public const int tab2 = 2131296271;
			
			// aapt resource value: 0x7F090010
			public const int text = 2131296272;
			
			// aapt resource value: 0x7F090011
			public const int title = 2131296273;
			
			// aapt resource value: 0x7F090012
			public const int version_number = 2131296274;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0005
			public const int button_primary = 2131361797;
			
			// aapt resource value: 0x7F0A0000
			public const int MasterDetailTheme = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int MasterDetailTheme_Base = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int SplashTheme = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int SplashTheme_Base = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int Widget_CardContent = 2131361796;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
